[package]
name = "smashout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11"
console_error_panic_hook = "0.1.5"
lazy_static = "1.4.0"
